[package]
name = "ast_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
ast_model = { version = "0.1.0", path = "../ast_model" }
serde = { version = "1.0.228", features = ["derive"] }
sol_tokenizer = { version = "0.1.0", path = "../../sol_tokenizer" }
sol_utils = { version = "0.1.0", path = "../../sol_utils"}
